[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "https://www.loumistral.fr/*"
  to   = "https://loumistral.fr/:splat"
  status = 301
  force = true
